# Пример использования:
# reader = CsvReader('data.csv')
# data = reader.read()
# processor = DataProcessor(data, reader.headers)
# processor.select(['Name', 'Stars']).sort('Stars', reverse=True)
# result = processor.execute()
# user = User()
# user.save_query('top_starred', processor)
# result = processor.execute()
# median_val = DataStatistics.median_size(result)
# max_starred = DataStatistics.max_starred_repo(result)
# no_lang = DataStatistics.repos_without_language(result)
# top_commits = DataStatistics.top_commits(result)
# DataStatistics.save_statistics(max_starred, 'max_starred.csv')
