name: Testing github_repo_api

on: push

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - black
          - ruff
          - mypy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        uses: astral-sh/setup-uv@v3

      - name: Install deps
        run: uv sync

      - name: Run lint check
        run: uv run pre-commit run -a ${{ matrix.cmd }}
